### ISSUE TITLE
Why not translate the project to other languages?

### ISSUE THREAD

**Issue by brunopulis** [a11yproject/a11yproject.com#325]
Hello everynone, 

I'm Brazilian and was thinking why not translate the project? 
In my city I created a group of a11y the meetup and wanted to spread great content like the design.

Would it be a possibility begin translations of the project?

**Comment by joe-watkins** [comment]
@brunopulis There is a Google Translate feature in the footer of the site.. is that not doing a good enough job?

**Comment by brunopulis** [comment]
@joe-watkins Sometimes the translation is not correct I will look carefully here and I report to you. : D

**Comment by elderhsouza** [comment]
We've already discussed the localization of the content a while ago, one of the issues was that multi-language content was not a core functionality in Jekyll at at he time.

Since then, I'm not sure if this was integrated, but there are a couple of plugins that implements this, one of them is https://github.com/screeninteraction/jekyll-multiple-languages-plugin developed by @kurtsson (he had already mentioned this in the old thread but since the issue was closed after the Google Translate integration, I don't think a lot o people have seen it).

I think the key point is that translation isn't really localization, especially in terms of technical jargon, which is abundant in our case, so if we could find a solution to really localize the content to other languages, as said before, that's just good accessibility. ;)

I think it's at least worth a try.

**Comment by OlivierNourry** [comment]
+1 on that one.
It's been observed that not having resources in their native languages can be a major roadblock for developers willing to apply the WCAG (http://www.accessiq.org/news/w3c-column/2015/07/does-wcag-have-a-language-barrier). W3C has significant issues with translating their considerable amount of resources in other languages. For projects such as this one, it's even more relevant to propose translated versions of the contents, as they are meant to be much simpler to consume than the WCAG. 
English speakers already enjoy a wealth of well-written, high-quality a11y resources. I think it would be a smart move to propose to the community a way to contribute and share human-made translations (cause, no, Google translations algorithms aren't good enough - could make some parts unintelligible sometimes).

**Comment by arkhi** [comment]
Anybody hasa clearer idea of how translations could be implemented?

I won’t probably go through the building process, but I would definitively like to help translate, at least the checklist as a start.

**Comment by joe-watkins** [comment]
Hello all :)

It would be totally cool if a11y-project was translated into many different languages but translation is a huge undertaking and a lot of work to maintain. Every time a change is made to a page it must be updated on every translated page as well. So the likelihood of getting the site human translated and maintained at this point doesn't seem to be in the cards.

We also have some technical issues being hosted on GitHub and the fact that we are using Jekyll.

If someone would like to create a pull request and translate a particular page we could review and consider a way for users to get to this content.

The content on this site changes quite often. Outdated and unmaintained documentation is just as bad as untranslated content. We'll be happy to review PR
