### ISSUE TITLE
Screen Readers and Javascript Compatibility 

### ISSUE THREAD

**Issue by Pdxd** [a11yproject/a11yproject.com#326]
I know that web aim has provided the metric that a majority of screen reader users also have JS turned on. (90%+). This does not mean that they have the best experience with it. 

Recently, I was at an a11y conference where they had a panel of users with a multitude of challenges of whom all use the Web in their own way. They all say their biggest peeve is sites that are heavy in Javascript often crash their screen readers. And they tend to use the common ones like jaws.  

Has anyone done any performance testing on this? I'm not very technical but I think it might be  worth an investigation by someone who is JS savvy.

**Comment by davatron5000** [comment]
> They all say their biggest peeve is sites that are heavy in Javascript often crash their screen readers

Crashing? Like they have to restart JAWS? Or crashing like they are no longer able to navigate the page because the DOM was updated?

> Has anyone done any performance testing on this? 

I haven't seen/heard any performance testing on this. We'd probably need to know of a JS-heavy site that is known to crash screen readers before proceeding. Or, what would probably be better and more responsible is to open issues with the offending projects/sites letting them know their website crashes screen readers. Then do a write-up/postmortem on the problems and how they were solved.

It's a good idea, but maybe it's more of a personal blog post. We're more on the educational vs. analytical side of things.

Thanks again for bringing this up. Closing due to "not enough information"
