### ISSUE TITLE
Small screen navigation JS-only

### ISSUE THREAD

**Issue by gablaxian** [a11yproject/a11yproject.com#366]
Using Chrome in device testing mode, I had JS turned off and noticed that the drop down menu 'handle' did not function and neither did it skip to any secondary links area.

If JS is a requirement to open a list of links, a nice fallback is to have the list of links also at the bottom of the page and the <a> just jumps to those. As it stands, the handle is a link which links nowhere and, as such, is not a link. Should probably be a button in this case.

**Comment by jeryj** [comment]
The redesign (that's basically complete and ready to go) just outputs a list of links on small screens. So, maybe we should just test the redesign a bit and push it out rather than fix this on the current site design?

![screen shot 2015-11-04 at 8 47 42 am](https://cloud.githubusercontent.com/assets/967608/10941407/e6f3570c-82d0-11e5-8072-3fa7d1dce2df.png)

**Comment by gablaxian** [comment]
I would agree :)
