### ISSUE TITLE
Article: Color Contrast

### ISSUE THREAD

**Issue by RachelRVasquez** [a11yproject/a11yproject.com#377]
Here's another work in progress:

https://gist.github.com/RachelRVasquez/d1c1e99cfdd9780c5918

Tackling it from the article list under "Concepts": https://github.com/a11yproject/a11yproject.com/issues/12

Let me know if it sounds like it's going in the right direction so far. :-)

**Comment by RachelRVasquez** [comment]
I think I'm just about done with this one - just not quite sure how I can wrap it up?

**Comment by thierryk** [comment]
You could mention [high-contrast mode](https://developer.yahoo.com/blogs/ydn/techniques-high-contrast-friendly-icons-153038779.html) as few people are aware of this issue.

**Comment by RachelRVasquez** [comment]
Added a link from W3C about high contrast style switchers and mentioned in the "What else can we do" list about providing tools to adjust to a lower/higher contrast. It sounds like it might be useful to write additional articles or checklists about techniques for high and low contrast tools.

**Comment by thierryk** [comment]
@RachelRVasquez 

When it comes to high-contrast mode, it is more about techniques than tools, so I'm not sure the W3C link is of much help&mdash;why not linking to the article I mentioned earlier?

**Comment by RachelRVasquez** [comment]
Added. :+1:

**Comment by davatron5000** [comment]
:+1: This is great @RachelRVasquez! Do you need help article-izing this? Or do you want to make a pull request?

**Comment by RachelRVasquez** [comment]
@davatron5000 I do need help actually. :-) I wasn't sure what the process was from this point onward. If you can tell me how to "article-ize" I'd like to learn how.

**Comment by davatron5000** [comment]
Article-izing is maybe a bit difficult if you're not familiar with the Jekyll system. Here's the process in a nutshell:

1. Download the project in something like [GitHub Desktop](https://desktop.github.com/) or however you do `git`
1. Open the project folder, then open `_posts`
1. Duplicate `example_post.md` (https://github.com/a11yproject/a11yproject.com/blob/gh-pages/_posts/example-post.md) and retitle the file `YYYY-MM-DD-seo-title-slug.md`
1. Open the file in a text editor and paste your text below the `---` metadata
1. Fill out the metadata and set `published: true`
1. Save the file
1. "Commit" the file.
1. Use the "Pull Request" button to send a pull request.

You can send your article up without ever using Jekyll. So that's nice. **BUT** If that seems overwhelming (and it was to me typing it out :stuck_out_tongue_winking_eye: ), I'd be more than happy to do it. 

I could also make a screencast to show how it works for in the future.

**Comment by RachelRVasquez** [comment]
@davatron5000 It looks like I got it. :-)

https://github.com/a11yproject/a11yproject.com/pull/382
