### ISSUE TITLE
Site Flashes in Firefox

### ISSUE THREAD

**Issue by MarjaE2** [a11yproject/a11yproject.com#396]
If I try to scroll around this site in Firefox, I get hit by flashing black notes. These can hurt and can trigger migraines. Similar bugs affect many other sites in Firefox.

**Comment by jeryj** [comment]
Hi @MarjaE2, Sorry to hear that! Do you mean the flashing black notes happen on the new [http://a11yproject.com](http://a11yproject.com) site design? Also, are you on a Windows computer? I see a few bugs reported for Firefox on Windows that sound similar to what you're describing. Just trying to get some more info so we can try to fix it.

**Comment by MarjaE2** [comment]
I currently use OS X. Yes, flashing black notes happen there, and flashing white menus on the Mozilla support site, and similar bugs elsewhere.

**Comment by jeryj** [comment]
Hi @MarjaE2 - We've tried reproducing it, but haven't had any success. Could you give us a few more details to help us troubleshoot the issue?

- What version of OS X are you using?
- What version of Firefox are you using? You can find this by going to Firefox > About Firefox.
- Which URLs on the a11yproject.org website flicker when scrolled?
    - http://a11yproject.com/ (Yes/No)
    - http://a11yproject.com/about.html (Yes/No)
    - http://a11yproject.com/checklist.html (Yes/No)
- What steps will reproduce the problem? Example:
    1. Zooming in on the browser to 200%
    2. Opening 10+ tabs in the browser.
    3. ...

Send over any notes or thoughts you might have about how we can reproduce the problem, or maybe even a screencapture image or video. We want to make sure we do whatever we can to figure this one out!

**Comment by MarjaE2** [comment]
OS X. 10.11.3

Firefox 43.0.4 w/ several fixes and extensions

2 tabs right now. Scroll over any of the blue "Article" buttons or usernames. It's behaving better than Mozilla's support site right now, but it's flashing.

**Comment by jeryj** [comment]
@MarjaE2 Do you mean that scrolling over the article links on the homepage of a11yproject.com cause a flicker?

Can you tell me specifically which pages cause the flashing on each of these pages at a11yproject.com?
- http://a11yproject.com/ (Yes or No. If no, when does the flashing occur.)
- http://a11yproject.com/about.html (Yes or No. If no, when does the flashing occur.)
- http://a11yproject.com/checklist.html (Yes or No. If no, when does the flashing occur.)

I have v43.0.4 installed now, so I'm testing it, but still can't get the flashing to occur. Can you tell me if you're zoomed in your browser at all, or which extensions you have installed? What do you mean by "several fixes" on Firefox? I'm not familiar with what those might be.

Still trying to figure this one out! Thanks for the help isolating the issue.

**Comment by MarjaE2** [comment]
here, this page, here

https://github.com/a11yproject/a11yproject.com/issues

**Comment by jeryj** [comment]
@MarjaE2 Thanks for giving me the page URL. I think I understand now: you mean the black flash that happens when you scroll your mouse/cursor over the blue Article buttons on github.com. Scrolling over the blue Article button flashes a black "tooltip" with white text, and the fact that it flashes in is jarring, hurts, and can trigger migraines. 

If, instead of flashing in, it was a smoother animation, such as a "fade in" or "slide in", would that be less likely to hurt and trigger migraines? 

Also, just to clarify what the A11Y Project is: github.com is what we (the A11y Project) use to plan and manage the website http://a11yproject.com. The website github.com is not something we control or work on. However, I'd be happy to file an issue for you with github.com to let them know that their tooltip flash hurts and can cause migraines.

**Comment by MarjaE2** [comment]
"If, instead of flashing in, it was a smoother animation, such as a "fade in" or "slide in", would that be less likely to hurt and trigger migraines?"

I can't speak for everyone, but for me, it would be even worse and more likely. Flashing is bad. Animation is worse. Zooming is agony.
