### ISSUE TITLE
Review "Resources" for quality

### ISSUE THREAD

**Issue by AllThingsSmitty** [a11yproject/a11yproject.com#411]
As [previously mentioned](https://github.com/a11yproject/a11yproject.com/issues/410#issuecomment-207454290), it's worth going through this material to ensure we have the "best of" quality resources for A11Y Project.

**Comment by webuxr** [comment]
@AllThingsSmitty FYI, I just submitted PR #454. That work covers a lot of what I think you're talking about (clean-up, weighing the quality of similar links, preventing duplicates, overall categorization, etc.). 

At the very least, I figured it'd be helpful to cross-link these issues.

It's a start.

**Comment by davatron5000** [comment]
This issue is near and dear to my heart but I think it'd help to be more concrete on our goals. For me it's prioritizing freshness and relevancy. If a tool or blog post isn't really recommended by people anymore, we should phase it out to reduce noise on this page.

The best way I see it working is someone volunteers to be the Resource Czar and make executive decisions on freshness and relevancy. It's probably 2hrs of work click thru each link and making tough decisions. Any volunteers?

**Comment by webuxr** [comment]
Curating content posted to any page of [a11yproject.com](a11yproject.com) is certainly a good idea. So is having one person responsible for doing the curating (like the Resources Czar @davatron5000 mentioned). I do however, think it's an on-going process, one that is the responsibility of the community (at least for now). I also think this task of curating and pruning content is one that will, and should, be an on-going task. Keeping content fresh and applicable is a constant struggle everywhere on the Interwebs.

Plus, I think we need a way to define _and qualify_ what "best of" actually means. I propose this issue be closed and a new issue created to do just that: **Define a method for qualifying quality Resources content** (and perhaps a sister issue for Checklist content).

Anyhow, @AllThingsSmitty would have dibs on creating the new issue (if he wants to)? Or I can too.

Thoughts overall?

**Comment by AllThingsSmitty** [comment]
I can take a stab at it, present it to the group and get some feedback.

**Comment by svinkle** [comment]
@AllThingsSmitty Want to close this and start that new thread?

**Comment by AllThingsSmitty** [comment]
@svinkle agreed.
