### ISSUE TITLE
Bug: Accessibility checklist has invalid/duplicate `<legend>`

### ISSUE THREAD

**Issue by chrisgeary92** [a11yproject/a11yproject.com#488]
It seems one of the `<fieldset>` tags on the [http://a11yproject.com/checklist.html](/checklist.html) page has two `<legend>` tags as direct children. As far as I am aware, this is incorrect usage of the `<legend>` as they must be the first child of a `<fieldset>` which the latter is not.

The two in offending tags are:

* `<legend>Color and Contrast</legend>`
* `<legend>Test for different types of color blindness.</legend>`

*Suggested fix:*

Add `</fieldset><fieldset>` on [line 187](https://github.com/a11yproject/a11yproject.com/blob/gh-pages/checklist.html#L187)

**Comment by scottaohara** [comment]
Splitting this into two ```<fieldsets>``` would definitely fix the validation issue, but I wonder if instead some more fundamental wording changes were made to keep the related color checks in the same fieldset group, and remove the second legend instead?

Otherwise, there'd be two color fieldsets, with the first only containing a single checkbox...

Thoughts?

**Comment by joe-watkins** [comment]
@chrisgeary92 Good catch! I've split those into two for now in #489

@scottaohara has a good point about content being reworked there to fall under one color test umbrella, but this ducktape fix will do for now. Tnx!
