### ISSUE TITLE
Pattern: Accessible autocomplete

### ISSUE THREAD

**Issue by svinkle** [a11yproject/a11yproject.com#501]
This autocomplete/combobox is pretty well done. https://github.com/alphagov/accessible-autocomplete (Examples: https://alphagov.github.io/accessible-autocomplete/examples/)

How do folks feel about linking to a GitHub repo instead of a CodePen? I know it's not ideal as there's more digging; perhaps this could be linked elsewhere on the site?

**Comment by scottaohara** [comment]
my 2 cents, but I'd welcome patterns that linked to pages other than codepen, since it requires a pattern to be ported to codepen, which could then make it out of date with a github repo where it's actually maintained. 

Also testing pens, with screen readers, can be a bit annoying if one doesn't switch over to the full screen mode.

**Comment by svinkle** [comment]
Right, I wouldn't expect someone create a new pen based on the repo, that'd be a maintenance nightmare. It's just that this method requires a bit more effort to find the code/demo in question, depending on which resource we link to.

I agree with the sentiment that it doesn't _have_ to be CodePen; any sort of code demo site would suffice.

**Comment by svinkle** [comment]
Closing this as I'll probably make my own example to contribute, someday.
