### ISSUE TITLE
Pattern: Accessible Floating Labels

### ISSUE THREAD

**Issue by svinkle** [a11yproject/a11yproject.com#505]
I'm not sure how I feel about floating labels, nor have I been able to put them through a usability testing session yet, but I made up this demo. I figure if someone's going to add this feature to a project they should have an accessible option to choose from.

https://codepen.io/svinkle/pen/NvazGb

What do folks think?

**Comment by scottaohara** [comment]
i'm legit torn on this.

i really like what you did but i'm wobbling on the following:

1. I like how you used the placeholder as the label and then animated in the real label on text entry...but this also then becomes an issue because the placeholder isn't acting as a 'placeholder', which to me isn't that big of a deal...but that leads me to point 2...
2. the placeholder text fails color contrast checks...which can easily be fixed...but then we're running into the issue of "wait, is this field already filled out?" 

Here's an article, from May, that [argues against floating labels](https://medium.com/simple-human/floating-labels-are-a-bad-idea-82edb64220f6).  There are some debates in the comments that are worth reading (though, as with many comments, you're going to have to sift through some less than helpful ones too)

One thing that I took away from one of the comments was a "this isn't a real problem if you design it appropriately"  while the person that said it didn't have a solid argument, in my opinion, of what would make for a good design, i do think there is some truth to that...but it'd start getting into some opinionated territory as to what constitutes a well designed AND accessible floating label example. 

I hope this post sparks an idea for you, scott.  sorry it's not more direct/helpful

**Comment by svinkle** [comment]
@scottaohara Thanks for the feedback!

Some quick points:

1. The `placeholder` can still act as the `placeholder`, just need to "adjust" the text accordingly with the "label" and example text.
2. I've fixed the contrast ratio: 

    ```scss
    &::placeholder {
      color: #767676;  // 4.5:1
    }
    ```
3. I'm not so much arguing _for_ using this, just that if a design does call for such a requirement that we have something decent available for folks to grab and implement. Perhaps there could be an attached note, "use with caution," and link to some article.

I was loosely basing the functionality on what's currently on the [Shopify](https://shopify.com) homepage. When it comes to the question of, "good design," perhaps it makes sense to "wrap" the `input` and floating `label` as seen there? At least then there's no question that the newly appeared text is associate with the current `input` element.

I'll have a read through the article and see what's suggested there.

**Comment by scottaohara** [comment]
in response:

1. good call on the 'adjustment'.  
2. noice
3. understood, and in that context then i think you got something solid here.

one thing i noticed while testing w/ VO on macOS 10.12.6:
![focus ring on invisible object after moving focus past the name input](https://user-images.githubusercontent.com/4152514/29296335-a544d4fa-8127-11e7-8566-1de8b9ba9f5a.png)

a second 'scott' is in the tab order after trying to move past the username input, repeating the name in the input, but not there if i don't add anything to the input... i assume this is a VO bug?  can't reproduce w/out VO being on, and only in Safari

**Comment by svinkle** [comment]
@scottaohara Totally agree with that article. I really think this technique _should not_ be used. That said, design is sometimes set in place and a compromise cannot be made. In that case, at least use something _somewhat_ accessible. I'll add this link as an aside to the pen.

I think you might be experiencing the same thing I do when testing with Safari; after inserting text, moving away then back again, VO announces the text again, stating you've "unselected" the text. Otherwise, I'm unable to recreate the issue.

**Comment by svinkle** [comment]
Note on why this demo exists and is recommended to _not_ be used has been added.

**Comment by svinkle** [comment]
Small update on this. I had some SA folks help review and test this (@dpersing, @gavinogston, and @joe-watkins 👍) and it's working in:

- Edge + JAWS
- IE11 + JAWS
- Firefox + NVDA
- Safari + VoiceOver
- Chrome + TalkBack

Also added Babel & `babel-polyfill` for older browser support. I think this thing is in good shape. 🛳?
