### ISSUE TITLE
Securing a11yproject.com domain

### ISSUE THREAD

**Issue by svinkle** [a11yproject/a11yproject.com#559]
To help with security and privacy of our readers, let's add `https` to the `a11yproject.com` domain.

Use this [handy guide from Cloudflare](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/) as a resource (I've secured all my domains using this method; works well!)

When complete, any existing links to the project should forward to the `SSL` enabled domain by default. 🙌

**Comment by rstamper-ai** [comment]
It's easy to setup and you forgot the best part. Cloudflare gives you SSL for free, as long as the site isn't commercial :)

**Comment by davatron5000** [comment]
Okay. I think I've set everything up right on Cloudflare but getting a `net::ERR_CERT_COMMON_NAME_INVALID` error that's showing the scary "This site's not secure" when you visit https://a11yproject.com

The advice from the FAQ is this:

> The Cloudflare-issued SSL certificate is not yet active for your domain
> When you first sign up your domain with Cloudflare, The Cloudflare-issued SSL certificates may have not yet been issued. Please allow 15 minutes (on paid plans) or 24 hour (on our Free plan) for this process to complete. You will know if your SSL certificates are active through your CloudFlare dashboard under the Crypto tab.

Our status is showing as "Active", but maybe we just wait and check it out tomorrow.

**Comment by svinkle** [comment]
From experience it does take a bit of time for everything involved (DNS, certs, etc) to update. Eventually it should work itself out and, depending on how you set things up, should default/reroute to `https`.

**Comment by rstamper-ai** [comment]
Hello Dave, 

https://www.sslshopper.com/ssl-checker.html#hostname=https://a11yproject.com/
They say your SSL is fine. I'm however having trouble in my browser too as it's seeing a *.github.com certificate instead of yours. 
Your DNS records look fine too so it may just be a matter of propagation:
https://intodns.com/a11yproject.com

**Comment by davatron5000** [comment]
😫 welp. took the whole site down (even `http://`) because of auto-forwarding to HTTPS. I disabled that and got `http://` back online. Once we can confirm `https://` is up, I'll re-engage HTTPS upgrading.

**Comment by davatron5000** [comment]
🎉 hey hey hey! I got it all working. I had to downgrade from what the guide recommended to a `Full` certificate instead of a `Full (Strict)`. Re-enabled auto-upgrading and we're Green Locks ✅🔒 across the board.

http://a11yproject.com
https://a11yproject.com
http://www.a11yproject.com
https://www.a11yproject.com
http://a11yproject.com/posts/accessible-data-tables/
http://www.a11yproject.com/posts/accessible-data-tables/

Thanks for the help and the patience everyone.

**Comment by svinkle** [comment]
Woo! Nice work, @davatron5000! 🍻

**Comment by danielmatthew** [comment]
Nice one @davatron5000 \o/
