### ISSUE TITLE
Accessible <nav> with dropdowns

### ISSUE THREAD

**Issue by ajsaucier** [a11yproject/a11yproject.com#605]
[Codepen](https://codepen.io/ajsaucier/pen/OZOQox)

**Comment by ericwbailey** [comment]
Could you please provide more context for this issue? Is this a pattern you'd like to add to the site? Or something else?

**Comment by ajsaucier** [comment]
Sure, sorry about that. I read the Contributor Docs wrong.

There's a post idea for "HOWTO: Make an accessible <nav> with dropdowns". This Codepen has an accessible nav that I made and would like to add to the site, if appropriate. I also posted an article about it on my own site, but for a11yproject I'd add to the actual steps for a how-to if you guys think the code and result in the Codepen are worthwhile.

**Comment by scottaohara** [comment]
from what i recall in reviewing the markup prior to the link being taken down, it seemed like you had the following structure:
```
<li role="menuitem">
  <a href="#">...</a>
</li>
```
which is incorrect as the `menuitem` is meant to be the focusable / actionable element in the sort of pattern you were looking to produce.  

If I misremembered your markup, then apologies / never mind :)

**Comment by ajsaucier** [comment]
You're absolutely correct, thanks. I had them on three of the `<li>`s (not sure how I just skipped the others) but I fixed that. Thank you!

**Comment by ValorNaram** [comment]
I have written a accessible navigation as part of my _control website via keyboard only_ sub project from project _isl_. My question is: Should I show my code, because @ajsaucier is working on an accessible navigation too and authored this issue. I don't want to fool persons by showing my stuff while knowing there is another, who work on the same thing.

That's why I ask before I show.

**Comment by svinkle** [comment]
@ajsaucier 
> I'm not sure how classes can make it less dependent on the HTML.

By applying BEM style classes you only need to select the class in question for both your CSS and JS. Sure, the structure of a menu is likely not going to change, but who knows down the road. It's good practice to separate these things out.

**Comment by ajsaucier** [comment]
Okay, I think I updated it correctly(?). I added the BEM in the pattern of the article you linked to, revised the CSS and JS for the selectors and classes added/removed.

**Comment by scottaohara** [comment]
Hi @ajsaucier 
Thanks for the updates.  

Looking through this some more though, I've come across a few issues when using it with VoiceOver and JAWS.  Rather than giving you a punch list, I'd suggest referencing [the ARIA menubar pattern](http://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html), as this seems to be the pattern/interaction you're looking to produce.  

If you have any specific questions, feel free to reach out to us though :)

**Comment by ajsaucier** [comment]
Oh...wow. That’s really great. Thanks for that link, I’ll be using that in the future. Beats mine by a mile.

**Comment by scottaohara** [comment]
it depends on what your end goal is, honestly.

that could be a very good example, or it might be wildly inappropriate.  it completely depends on the project and if a navigation should be populated with links, or menu items.

**Comment by scottaohara** [comment]
closing this for now as we've hit the 6 month mark of inactivity.
thank you to everyone involved :)
