### ISSUE TITLE
Article: ARIA properties

### ISSUE THREAD

**Issue by alexroseb** [a11yproject/a11yproject.com#620]
I started with a basic list of the properties with categories and descriptions. Idea from #12.
The Gist is at https://gist.github.com/alexroseb/89cc026cc34786160404dcefaa9262e5 - please review and give feedback! I'm not sure how to go from the Gist to getting it on the site.

**Comment by ericwbailey** [comment]
This is looking great!

Could I trouble you to link each property back to the specification? That way there's always a reference to the canonical documentation, in case things are updated at a later date.

**Comment by alexroseb** [comment]
@ericwbailey Done!

**Comment by scottaohara** [comment]
Another bit of feedback, but would you mind creating a different example for your intro?

The example you provided, adding a "label" to a `table` element, can and should be done with the `caption` element, rather than using ARIA.

It'd be good to demonstrate an example of a situation where HTML needs ARIA.  e.g. expressing a pressed or expanded state for a `button` is not something that can be done with HTML alone.

Thanks :)

**Comment by alexroseb** [comment]
@scottaohara Oh, very good point - changed to `aria-haspopup` for a button.

**Comment by ericwbailey** [comment]
Closed via https://github.com/a11yproject/a11yproject.com/pull/623
