### ISSUE TITLE
Rethink the homepage's content

### ISSUE THREAD

**Issue by ericwbailey** [a11yproject/a11yproject.com#719]
Right now it feels a little strange to be just dumped into the post categories with little explanation. What I'd like to do is:

- Explain what "a11y" means and point to [this article](https://a11yproject.com/posts/a11y-and-other-numeronyms/). I think it's important to stress how "a11y" speaks _specifically_ to web accessibility concerns.
- Point to the checklist as a good place to get started if you don't know where to begin (and possibly revise checklist content, as well).
- Surface other site content in the form of highlights. I'm thinking things like the latest post, featured members of the a11y community, new resources and events, that sort of thing.

**Comment by dengeist** [comment]
Wish I had something more useful to say than "I agree." I think explaining a11y is _critical_, because people in this community often assume it is understood. Sometimes it isn't, and I default to saying "web accessibility" wherever I can because of it.

**Comment by webuxr** [comment]
For @ericwbailey's first point, what about doing something as simple as adding an abbreviation element to the H1?
```
<h1 class="a11y-title">
    The <abbr title="A11Y is a numeronym or shorthand for accessibility">A11Y</abbr> Project
</h1>
```

I mean, it might seem a tad hypocritical, since the numeronyms primer article states that A11Y is not an abbreviation (nor an acronym) but a numeronym instead. Regardless, the `<acronym>` element is discontinued and I'm not aware of a `<nuronym>` element that would suffice :)

Or, perhaps this is an opportunity to use `<dfn>` and `<abbr>` in tandem as described on [MDN here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dfn#Using_abbreviations_and_definitions_together)?

The only drawback here is that neither option allows for the "A11Y" text to be linkable to [Scott's post](https://a11yproject.com/posts/a11y-and-other-numeronyms/).

![a117y-not-an-abbr-but-this-is-simple](https://user-images.githubusercontent.com/1559023/58824457-bddd5880-8601-11e9-9834-05c0dfb131f2.jpg)

**Comment by ericwbailey** [comment]
@webuxr It's a nice idea, but I try to [follow Steve Faulkner's advice](https://developer.paciellogroup.com/blog/2019/03/short-note-the-abbreviation-appreciation-society/) when it comes to using `abbr`.

Here's a little sneak peek of how we're going to handle it with the redesign 🙂 

<img width="556" alt="a11y stands for accessibility." src="https://user-images.githubusercontent.com/634191/58840026-28a68800-8632-11e9-930a-e6476f7d6662.png">

**Comment by webuxr** [comment]
@ericwbailey That looks sweet, thanks for sharing. And I agree with Faulkner's thoughts about `abbr` and the not-so-accessible `title=""` attribute.

Anyhow, I'm looking forward to helping more and seeing things in the [redesign project](https://github.com/a11yproject/a11yproject.com/projects/1) gain momentum.

Keep me in mind for any front-end/UI dev tasks and I'll do my best to make myself available.

**Comment by ericwbailey** [comment]
I think we have addressed these concerns with @tatianamac's redesign work. Closing this.
