### ISSUE TITLE
Table of Contents / Make Sticky on Scroll

### ISSUE THREAD

**Issue by dennisgaebel** [a11yproject/a11yproject.com#955]
The Table of Contents like example shown below could use some love. The resources listed are extremely long so having some sort of sticky nav effect for the TOC would be great. Would also help avoid long scrolls back to the TOC again to find another item.

![Screen Shot 2020-07-15 at 8 53 42 PM](https://user-images.githubusercontent.com/13485205/87614259-85052380-c6dd-11ea-9271-ac6f8ecf68f3.png)

**Comment by ericwbailey** [comment]
We're actually specifically avoiding sticky elements. During testing our sticky elements—especially larger ones—greatly impeded the ability for low vision users to navigate the site. 

Long story short: it obscures significant portions of the page and crowds out main content. This is in keeping with reports of sticky content treatments with other websites.

**Comment by dennisgaebel** [comment]
@ericwbailey So to make sure I'm clear on this essentially making the TOC stick on scroll is causing issues yeah? If that's the case feel free to close this, but if there's a way to make that kind of interaction happen without hurting low vision users that would be swell. I like having access to the TOC for navigational purposes, and also also helps to avoid scrolling back up each time. Maybe a low vision toggle for the TOC that turns off the sticky effect? Just a thought 🤝

**Comment by ericwbailey** [comment]
Yeah. The other issue would be ToCs where the height is taller than the viewport. I've seen some implementations where portions stick (I think GitHub has some nice examples), but it'd be hard to chop something like the Resources ToC up.

Let me noodle on this some, and leave it open in case others want to chime in.

**Comment by StommePoes** [comment]
Some thoughts and ideas:

I tell people who are hot on stickies to check viewport heights with CSS-- people with huge fancy monitors and good eyes would have a calculated viewport height high enough to have sticky crap, while the rest of us would have the content scroll.

Another solution is a control to slide the ToC to a narrow state, so they steal less room from the main page content. Lots of dashboards do this, like Jira, or those awful 3-panel web email applications.

The ToC could be a separate scrollable region, though these really, really, really suck esp with keyboard, but they ensure you don't end up with this:
https://stommepoes.nl/Access/Low-vision/img/tmobile.jpg
[alt=T-Mobile's website starts with a sticky header and a very, very long menu. The page is clearly scrolled down a bit, yet only shows the top of the menu.]

Since mouse users are generally unaware of keyboard shortcuts to reach the tops of sites (or are using a tablet and calling up an onscreen keyboard to jump to the top is a pain in the butt), a skip link to the ToC could also possibly option.

**Comment by ericwbailey** [comment]
The ToC sckip link is an interesting idea. We originally had something similar, but it was voiced that the extra skipnav prompt was clutter. The details/summary was the compromise, but we need to persist collapsed/expanded state across pages for it to be really effective.

**Comment by dennisgaebel** [comment]
Maybe at the end of each section you make a "back to toc" link? A simple href id link FTW

**Comment by StommePoes** [comment]
^ that would avoid the problems one gets with "floating" sticky back-to-tops, and could integrate into the design more.

The ToC might have to be visually labelled "ToC" though so non-biblionerds know what that is.

**Comment by ericwbailey** [comment]
Closed for inactivity.
